### ISSUE TITLE
GDAL import errors while running plugin.

### ISSUE THREAD

**Issue by homeless-computing** [caiohamamura/kuwaharafilter#1]
Windows 10 user (also stumbled upon this on Arch linux). 
There appears to be a problem while activating the plugin, installation went correctly though. The message reads as follows: ModuleNotFoundError: No module named 'gdal'. 
There might be something related to module import, GDAL or relative paths, but I can't be sure. 
Anyway, here is error traceback:

Couldn't load plugin 'kuw_filter' due to an error when calling its classFactory() method 

```
ModuleNotFoundError: No module named 'gdal' 
Traceback (most recent call last):
  File "D:\progs/qgis/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kuw_filter\__init__.py", line 27, in classFactory
    from .kuw_filter import kuw_filter
  File "D:\progs/qgis/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kuw_filter\kuw_filter.py", line 36, in 
    from .kuw_filterdialog import kuw_filterDialog
  File "D:\progs/qgis/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kuw_filter\kuw_filterdialog.py", line 32, in 
    from .filter import dofilter as doFilter
  File "D:\progs/qgis/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\kuw_filter\filter.py", line 3, in 
    import gdal, numpy, sys
  File "D:\progs/qgis/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'gdal'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.26.0-Buenos Aires Buenos Aires, 0aece2818e 

Python Path:
D:/progs/qgis/apps/qgis/./python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/progs/qgis/apps/qgis/./python/plugins
D:\progs\qgis\bin\python39.zip
D:\progs\qgis\apps\Python39\DLLs
D:\progs\qgis\apps\Python39\lib
D:\progs\qgis\bin
C:\Users\user\AppData\Roaming\Python\Python39\site-packages
D:\progs\qgis\apps\Python39
D:\progs\qgis\apps\Python39\lib\site-packages
D:\progs\qgis\apps\Python39\lib\site-packages\win32
D:\progs\qgis\apps\Python39\lib\site-packages\win32\lib
D:\progs\qgis\apps\Python39\lib\site-packages\Pythonwin
C:/Users/user/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by caiohamamura** [comment]
This seems to be unrelated to the plugin, but with the QGIS installation
itself since the plugin has no control over the python it will use. Make
sure you can open the python terminal in QGIS and run `import gdal` from
there.

Em qui, 30 de jun de 2022 03:10, homeless-computing <
***@***.***> escreveu:

**Comment by caiohamamura** [comment]
Maybe this had something to do with the `import gdal`, which in some systems is `from osgeo import gdal`, I've fixed that with a `try..except`. Check if this works now.
